### ISSUE TITLE
SyntaxError unexpected token in v0.0.5

### ISSUE THREAD

**Issue by magenbrot** [custom-cards/group-card#14]
Hi,

I've updated to 0.0.5 via HACS today and I'm getting this SyntaxError in the logs:

`2021-06-07 12:18:40 ERROR (MainThread) [frontend.js.latest.202106030] https://homeassistant.xxx.xxx/hacsfiles/group-card/group-card.js:54:17 Uncaught SyntaxError: Unexpected token '{'
`

best regards
Oli

**Comment by inhibitz** [comment]
confirm

**Comment by iantrich** [comment]
Fixed in https://github.com/custom-cards/group-card/releases/tag/0.0.6
