### ISSUE TITLE
HACS type missing

### ISSUE THREAD

**Issue by haakonstorm** [custom-cards/group-card#2]
# group-card installation

when adding to the list of lovelace resources, the text offered in HACS is missing a key piece of data:

```
When you add this to your lovelace configuration use this:
- url: /community_plugin/group-card/group-card.js
  type:  
```

Is it a `type: module` or a  `type: js` ?

**Comment by q1t1** [comment]
It's a module.

**Comment by iantrich** [comment]
updated readme
